# Generated by Django 5.1.4 on 2025-01-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mingma',
        ),
    ]
