# Generated by Django 5.1.4 on 2025-01-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quickstart', '0002_delete_mingma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mingma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
